# Basic `dependabot.yml` file

version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    # Look for `pyproject.toml` files in the `root` directory
    directory: "/"
    # Check pip for updates every day (weekdays)
    schedule:
      interval: "daily"
